### PR TITLE
Fix DSN scheme and minor typo in Readme 

### PR DESCRIPTION
**Pull request by mkoitka**
I've noticed an inconsistency in the Readme file of the plugin where the DSN scheme _(office-graph-api)_ differs from the one defined in the Transport Factory _(microsoft-graph-api)_. To ensure consistency and functionality, I suggest updating the Readme to align with the scheme defined in the code. However, if the intention is to adjust the scheme in the Transport Factory, I am happy to modify my pull request accordingly.

By the way, thank you for developing such a great plugin and for making it available open source! :tada:

### CODE REVIEW

**Comment by vitrus** [comment]
@mkoitka wow that is a nasty issue... good you found it! Will merge and re-release a version.

**Comment by mkoitka** [comment]
@vitrus Nice, thank you for your fast reaction!

**Comment by vitrus** [comment]
It is such a stupid mistake I made there (switched it around a few times, documented it incorrectly).

Because people might have installed it, concluded it did not work and installed something else (that does not allow for HTML e-mails or something like that :roll_eyes: ). It is however really cool to release this (we needed it at work) and see people actually use it!

**Comment by mkoitka** [comment]
Yeah, I can totally understand your worries about that. Though if a reasonably experienced developer should have stumbled across that error, he would have quickly found the solution to the problem and create a Pull Request. So all good. 😄

**Pull request merged**
